### ISSUE TITLE
Auto-scrolling does not always show the program element

### ISSUE THREAD

**Issue by tsantalis** [flozender/CodeTracker-Extension#38]
### Description
https://github.com/checkstyle/checkstyle/blob/8b9c27d9178228436813c99fbfb1af944e53a048/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
Select field `listeners` and track.

Click on the first change `b8ca6a5`
The scrolling goes to line 67 instead of line 64
![Screenshot from 2022-10-10 13-45-19](https://user-images.githubusercontent.com/1483516/194924809-e94ab6e0-6b17-4aab-9c17-39c88a7543b5.png)

The same thing happens with the second change `f1efb27`
![Screenshot from 2022-10-10 13-47-21](https://user-images.githubusercontent.com/1483516/194925113-ac21f0ce-7c7a-4003-b518-7ce3bb4e7f2c.png)

The same thing happens with the third change `f1afaf8`
The scrolling goes to line 59 instead of line 56
![Screenshot from 2022-10-10 13-50-10](https://user-images.githubusercontent.com/1483516/194925652-501103c2-e38b-4d5b-8b76-fa953f37a431.png)

In all cases, the scroll position should be a bit higher.

### Environment (if bug)

* Codetracker version: 1.1
* CodeTracker API version: 0.1.2
* Browser & version: Chrome
* OS & version: Ubuntu 22.04

**Comment by tsantalis** [comment]
The behavior is the same regardless of whether the **file tree** is shown or is hidden.

**Comment by flozender** [comment]
Thank you for reporting the issue. The auto-scrolling is done by GitHub when I provide it the ID for the exact line and it worked well when we tested the feature. Recently GitHub started scrolling a bit too far making the highlighted element not visible. I will have to report this issue to GitHub and make a workaround for the moment.

**Comment by flozender** [comment]
Fixed by GitHub.
