### ISSUE TITLE
Right-clicking on evolution hooks makes empty squares

### ISSUE THREAD

**Issue by tsantalis** [flozender/CodeTracker-Extension#39]
### Description
https://github.com/checkstyle/checkstyle/blob/8b9c27d9178228436813c99fbfb1af944e53a048/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L330
Select method `processFile` at line 330 and track.
Right-click on the evolution hook `77acd41` multiple times.
![Screenshot from 2022-10-10 14-03-25](https://user-images.githubusercontent.com/1483516/194927685-5ea67531-327e-4cbd-9dc1-9381d2b49807.png)

### Environment (if bug)

* Codetracker version: 1.1
* Codetracker API version: 0.1.2
* Browser & version: Chrome
* OS & version: Ubuntu 22.04

**Comment by tsantalis** [comment]
The evolution hook for methods was re-implemented in
https://github.com/jodavimehran/code-tracker/commit/c45d252366b0dac08b91851bd52fcdc3f27d487f#diff-4bd0a8a3a48fc0f30b70fdc998ab17cdc9c7f38dad015386d15c71d51649c9a5L34-L37

Is that the reason of the failure?
We are supposed to have system tests.
How was this problem not caught?

**Comment by flozender** [comment]
Yes, I believe that is the reason for failure. I was sidetracked by other tasks while working on the tests so I couldn't set up tests for evolution methods (Issue #17). I will do this shortly. Thank you for reporting the issue.

**Comment by tsantalis** [comment]
![Screenshot from 2022-10-14 07-29-53](https://user-images.githubusercontent.com/1483516/195837027-ebb31506-e4f8-40d6-9772-04f822443cba.png)

Right-click on `d46c2cf` causes exception. The start line 237 is the line the javadoc of the method starts. Method signature is in line 246
> Something went wrong: org.codetracker.api.CodeElementNotFoundException: Element src/main/java/com/puppycrawl/tools/checkstyle/Checker.java is not found in file 'process' at line 237!
